version: "3.9"
services:
  db:
    image: mongo:4.4.3
    container_name: mongodb
    restart: always
    # environment:
      # - MONGODB_USER: "user"
      # - MONGODB_PASS: "pass"
    volumes:
      - ./tmp/data/mongo/data:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db